version: "2.3"
services:
  flight-search-page:
    container_name: flight-search-page
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: vaskar/flight-search-page
    ports:
      - "3000:80"
